export * from './FirstPage/HeroScreen/HeroScreen'
export * from './FirstPage/SecondScreen/SecondScreen'
export * from './FirstPage/DirectionsScreen/DirectionsScreen'
export * from './FirstPage/ProcessScreen/ProcessScreen'
export * from './FirstPage/FifthScreen/FifthScreen'
export * from './FirstPage/SixthScreen/SixthScreen'
